server:
  port: 6060
  servlet:
    context-path: /api
  tomcat:
    threads:
      max: 50
      min-spare: 30
    max-connections: 500
    accept-count: 20
#  ssl:
#    enabled: true
#    bundle: localhostSSL
#
#spring:
#  ssl:
#    bundle:
#      pem:
#       localhostSSL:
#          keystore:
#            certificate: classpath:server.pem
#            private-key: classpath:server.key